version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Match your project's Node.js version
    commands:
      - echo Installing dependencies
  pre_build:
    commands:
      - npm install --legacy-peer-deps
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - '**/*'
  base-directory: dist  # Vite default build output directory
